### ISSUE TITLE
Remaster spartan armour

### ISSUE THREAD

**Issue by Lupus590** [34th-Para-Recon-Brimstone-Company/34th-PRC-Aux-Mod#100]
A lot of our spartan armour is WIP, we should revisit the textures for these items and check if they are still good enough or if we want to improve them.

**Comment by Lupus590** [comment]
Keeping in blocked for now as we have only recently made the spartan armour. We should let the current textures sit for a while before revisiting them.

**Comment by Vazya-H3lljumper** [comment]
MK IV is going to be updated alongside my MK V[B] textures.

**Comment by Lupus590** [comment]
On second thought, I think the textures are fine. If we change our mind we can make a new ticket,
