### ISSUE TITLE
Mjolnir HUD IFF System missing

### ISSUE THREAD

**Issue by Lupus590** [34th-Para-Recon-Brimstone-Company/34th-PRC-Aux-Mod#102]
**Describe the bug**
While messing around on the training map, I've discovered that the Mjolnir IFF system is non-functional for Cerberus slots. Concord tested as well and it works perfectly fine for the Zeus slot. Might need to look further into this later when Cerberus goes active with Mjolnir.

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**
The IFF system should either be on our off for every Mjolnir-equipped member for the sake of consistency.

**Screenshots**

**Additional context**
While this may not be an issue related to our mod, it is something that should be looked into since the system appears to work sometimes while breaking at other times.

**Comment by Vazya-H3lljumper** [comment]
Resolved. Mjolnir IFF system was turned off in the last update to the addon settings.
