### ISSUE TITLE
Mission-Load Preventing Bug from 34th Marine Uniform "Cannot open object halo_marine_02\null.p3d"

### ISSUE THREAD

**Issue by Lexicon-Prime** [34th-Para-Recon-Brimstone-Company/34th-PRC-Aux-Mod#103]
**Describe the bug**
When first loading a mission on a Dedicated Server, the mission will fail to launch on the server as players are unable to load the "halo_marine_02\null.p3d" resource, which is called for by at least our Red Urban Marine Uniform. This is called for at mission start if there exists an 3DEN-placed AI which is already wearing the armor.

**To Reproduce**
1. Create a mission with an AI wearing our red urban marine armor.
2. Launch it on Brimstone's server, not locally hosted.
3. You'll note the mission fails to load and you get that error.

**Expected behaviour**
The mission loads as usual, throwing no errors, especially about a "null.p3d".

**Screenshots**
![image](https://github.com/34th-Para-Recon-Brimstone-Company/34th-PRC-Aux-Mod/assets/131489713/f7e95f60-327a-4b9e-b541-77b9f992cf65)
![image](https://github.com/34th-Para-Recon-Brimstone-Company/34th-PRC-Aux-Mod/assets/131489713/5c00de66-bd63-40f0-8511-503c2a3a4b6f)

**Additional context**
This only prevents the initial loading of the scenario, as if launched anyways (such as from a Virtual Zeus slot) all further attempts to join the game lobby will not throw this error as the mission scenario is already loaded; This is the current workaround if you cannot start a mission in a player slot (as long as there are no AIs wearing our armor).

**Comment by Lexicon-Prime** [comment]
I will not add the "showstopper" label for now as there are workarounds which are readily available and easy to pull off, and I am doing some investigation with seeing if this occurs with our ODST armor and other armor variants.

**Comment by Lexicon-Prime** [comment]
Just confirmed, our ODST armor does not cause this error, it is just our marine armors.

**Comment by Lupus590** [comment]
I was aware of this already. It's the marine invisible vest from Misriah and not our bug.

**Comment by Lupus590** [comment]
I will report it upstream.

**Comment by Lupus590** [comment]
Closing as not our bug
