### ISSUE TITLE
Medic armour

### ISSUE THREAD

**Issue by Lupus590** [34th-Para-Recon-Brimstone-Company/34th-PRC-Aux-Mod#117]
**Is your feature request related to a problem? Please describe.**
It's sometimes hard to identify medics if you can't see the medic hardcase.

**Describe the solution you'd like**
Our custom armour with the medic icon on it. Preferably the same icon that our medic hardcase backpack has.
The medic icon should be on the shoulder plate, chest, and helmet.

**Comment by Vazya-H3lljumper** [comment]
I'll look into it a bit. If we have the icon on-hand then I'll set up a quick texture. Otherwise I'll add it to my list for the MA Marine armor update.

**Comment by Lupus590** [comment]
I think that @TheBrwnKidd has a medic icon from making the medical hardcase, it may be worth asking him.

**Comment by TheBrwnKidd** [comment]
I can send the medic emblem later today. Who needs it?

**Comment by Lupus590** [comment]
*The medic emblem was sent via Discord.*

@Vazya-H3lljumper since I think that you have more time than Kidd does at the moment, can you put it on the GitHub at `/useful pngs/` please?

**Comment by Lupus590** [comment]
There's already a lot fo armour combinations and we have vests with the medic symbol on it so I'm closing this issue.
