### ISSUE TITLE
Weapon Config edits/overrides (BR55 and Bulldog shotguns)

### ISSUE THREAD

**Issue by JackieCappy** [34th-Para-Recon-Brimstone-Company/34th-PRC-Aux-Mod#160]
Could we get updated configs for the following weapons...

- [x] Attachments for the 19th/Foundries BR-55/HB variants; that way we can remove the BR-45 from the arsenal.
 - `19_UNSC_br55` and variants copy attachments from `OPTRE_BR45`
- [x] Bulldog shotguns (all of them) to use the 19th/Foundries buckshot rounds.
 - `OPTRE_CQS48_Bulldog_Automatic`, `OPTRE_CQS48S_Chihuahua_Automatic`, `OPTRE_Bulldog_Riot_Shield` to use `12Rnd_8Gauge`  (May need to make custom mag but should use same rounds as that mag)
- [x] GRL-45 Illumination Flares
 - `MA_GRL_45` to use `ACE_40mm_Flare_White` (and other colour variants) (May need to make custom mag but should use same rounds as that mag)
- [x] GRL-45 HuntIR
 - `MA_GRL_45` to use `ACE_HuntIR_M203` (May need to make custom mag but should use same rounds as that mag)
- [x] Suppressor for SRS
 - `19_UNSC_SRS99AM` `OPTRE_SRS99D_Suppressor`

**Comment by Lupus590** [comment]
Jade has configs donated from SEC

**Comment by Lupus590** [comment]
Complications on bulldog, I need to provide a mag model for the magazine type.

I might need to define my own mag and use the UNSC Foundries ammo type.
