### ISSUE TITLE
Test/Demo of Misriah's new ODST uniforms, vests, and helmets

### ISSUE THREAD

**Issue by Lupus590** [34th-Para-Recon-Brimstone-Company/34th-PRC-Aux-Mod#181]
**Describe the solution you'd like**
Only do the Urban version, this is a test to see if we like Misriah's new ODST equipment.

**Additional context**
You will need to use the [Misriah Armory dev mod](https://steamcommunity.com/sharedfiles/filedetails/?id=2950991248)
Use the darker red from #180

**Comment by OverYandere** [comment]
We like it.
