### ISSUE TITLE
Our ODST armour lacks SPPs

### ISSUE THREAD

**Issue by Lupus590** [34th-Para-Recon-Brimstone-Company/34th-PRC-Aux-Mod#219]
The lack of SPPs makes making new textures harder.

Making an SPP for our current textures might be difficult, maybe it'll be easier to make new ODST textures?

**Comment by OverYandere** [comment]
Whether we continue to use non SPP files or SPPs having the original workflow file with any layers for patterns or other features will be important. The current problem with the ODST armors is that the files in the repo useful pngs folder are not current with the color / pattern scheming of our live ODST armors. I haven't checked but they're probably outdated for the marines too.

Additionally if we don't have SPPs, or maybe even if we do (I am not up to speed with Substance Painter yet), a texture artist creating a map for the armor bits and bobs would be helpful for future work on custom armor for the unit.

**Comment by Lupus590** [comment]
We might have to remake our armour in SPP format, in theory, we can take our textures and import them into Substance Painter but we won't get layers from doing that.

As for creating a map of the different bits of the texture, this is quite easy to do by drawing coloured squares over the texture file and then loading it as a texture ingame to see how the squares are distorted on the model.

**Comment by Lupus590** [comment]
Waiting for the new file to be uploaded to the google drive then we can close this.

Edit access on the google drive for me would also be nice.

**Comment by Lupus590** [comment]
Uploaded, thank you for the edit access.
