### ISSUE TITLE
Misriah update broke our ODST vests

### ISSUE THREAD

**Issue by Lupus590** [34th-Para-Recon-Brimstone-Company/34th-PRC-Aux-Mod#237]
**Describe the bug**
Vests gone

**To Reproduce**
Steps to reproduce the behaviour:
1. Look in arsenal
2. ???
3. ~~Profit~~ Weep

**Expected behaviour**
Vests not gone

**Additional context**
Should be just inherit from the new classname.

**Comment by OverYandere** [comment]
Fixed with latest release
