### ISSUE TITLE
Custom Halcyon Ship

### ISSUE THREAD

**Issue by Lupus590** [34th-Para-Recon-Brimstone-Company/34th-PRC-Aux-Mod#32]
**Describe the solution you'd like**
A custom ship texture with our ship name on it "The Gates Of Hell"

**Additional context**
![image](https://github.com/34th-Para-Recon-Brimstone-Company/34th-PRC-Aux-Mod/assets/9790321/11307e29-a1a5-4ceb-83ca-6d2e07a7323d)

**Comment by Lexicon-Prime** [comment]
"UNSC Gates of Hell" has been added as procedural textures in the "SatanSpawn" spawn composition, solving this issue in-game; We will not be able to get a custom texture going for this, as the 41st ODST's mod developers work is all internal and are casual objects made available to the public.

![Image](https://github.com/34th-Para-Recon-Brimstone-Company/34th-PRC-Aux-Mod/assets/131489713/05a6bb58-8b57-40c8-b118-730e7df3c25a)
