### ISSUE TITLE
Custom SPI

### ISSUE THREAD

**Issue by Lupus590** [34th-Para-Recon-Brimstone-Company/34th-PRC-Aux-Mod#77]
**Describe the solution you'd like**
Custom textures for SPI armour

**Additional context**
See #7 for stealth functionality

**Comment by Vazya-H3lljumper** [comment]
On hold after talking with Jade and Cappy about the quality of the baseline textures and model itself. The SPI set doesn't appear to be up to Misriah Armory's standards, so we don't believe it is a completed project. The current prototype textures that I have committed to the 34_SPI_Armor branch will suffice for now.

**Comment by Lupus590** [comment]
Closing for now, even if we are not entirely happy with it the texture that we have is good enough. We can make a new issue if we need to.
