### ISSUE TITLE
Lower guncase inventory size

### ISSUE THREAD

**Issue by Lupus590** [34th-Para-Recon-Brimstone-Company/34th-PRC-Aux-Mod#82]
**Describe the solution you'd like**
Bringing a gun case should be a trade-off, not an upgrade. Lowering the inventory capacity of the guncases will provide a negative to make it no longer a straight upgrade.

**Comment by Lexicon-Prime** [comment]
Currently debating the amount to lower capacity by; At this time, all bags store 35 or 37lbs, Guncase or not. Our rotary grenade launcher in use weighs 12lbs, and the M90 CAWS 6lbs. It looks like if I want a happy intermediate between all these I'll need to remove about 10lbs of capacity.

This would mean that for people willing to just store a lighter weapon in their backpack's inventory, they can do so, and probably equip it faster too. But for large weapons this will make a world of difference.

**Comment by Lupus590** [comment]
My instinct was to make the reduction be the size of an assault rifle since that's probably what is going to be living in there most of the time. My intent with the gun bags is to guarantee that the player using them will be able to fit their main weapon when swapping to their backup primary. It sucked when I was a sniper in another unit and I couldn't fit my sniper rifle in my backpack to pull out my assault rifle while being told to help breach a building.

**Comment by Lupus590** [comment]
All of the backpacks that we currently use are the same sizes, so I am closing this as I don't want an odd one out.
